language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_EMULATOR_LEVEL=android-22
    - ANDROID_API_LEVEL=android-28
    - ANDROID_BUILD_TOOL_VERSION=build-tools-28.0.3
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - $ANDROID_BUILD_TOOL_VERSION
  - $ANDROID_API_LEVEL
  - extra-android-m2repository
  - $ANDROID_EMULATOR_LEVEL
script:
  - travis_wait 90 ./gradlew build
after_success:
  - bash <(curl -s https://codecov.io/bash)
